---
- name: Init server
  hosts: all
  gather_facts: false
  become: true
  vars:
    - ssh_pub_key: "id_rsa.pub"
    - default_user_name: root
    - new_user_name: oliver
    - default_ssh_port: 22
    - new_ssh_port: 23521

  pre_tasks:
    - name: Setup localhost
      ansible.builtin.include_role:
        name: host
      tags: always

    - name: Investigate user and port
      ansible.builtin.include_role:
        name: investigate
      tags: always

    - ansible.builtin.debug:
        msg:
          - "User: {{ ansible_user }}"
          - "SSH Port: {{ ansible_port }}"
      tags: always

  tasks:
    - name: Gathering facts
      ansible.builtin.setup:
      tags: always

    - name: Setup passwordless sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^%sudo"
        line: "%sudo ALL=(ALL) NOPASSWD: ALL"
        validate: "/usr/sbin/visudo -cf %s"
      tags: sudo

    - name: Setup new user '{{ new_user_name }}'
      ansible.builtin.include_role:
        name: user
      tags: user

    - name: Restrict access
      ansible.builtin.include_role:
        name: restrict
      tags: restrict

    - name: Setup firewall
      ansible.builtin.include_role:
        name: firewall
      tags: firewall

    - name: Setup fail2ban
      ansible.builtin.include_role:
        name: fail2ban
      tags: fail2ban
