---

- name: Create sudo user '{{ new_user_name }}'
  ansible.builtin.user:
    name: "{{ new_user_name }}"
    state: present
    groups: sudo
    shell: /bin/bash
    append: true
    create_home: true
  register: user_created

- name: Set authorized key for new user
  ansible.posix.authorized_key:
    user: "{{ new_user_name }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/' + ssh_pub_key ) }}"
  when: user_created.changed