---

- name: Disallow SSH password authentication
  ansible.builtin.copy:
    src: disablePasswordAuth.conf
    dest: /etc/ssh/sshd_config.d/disablePasswordAuth.conf
  tags: restrict
  notify: restart sshd

- name: Disallow root login
  ansible.builtin.copy:
    src: disableRootLogin.conf
    dest: /etc/ssh/sshd_config.d/disableRootLogin.conf
  tags: restrict
  when: root_is_available
  notify: restart sshd

- name: Change ssh port
  ansible.builtin.template:
    src: ChangePort.j2
    dest: /etc/ssh/sshd_config.d/ChangePort.conf
  tags: restrict
  notify: restart sshd