---

- name: Disallow SSH password authentication
  ansible.builtin.copy:
    src: disablePasswordAuth.conf
    dest: /etc/ssh/sshd_config.d/disablePasswordAuth.conf
  notify: restart ssh

- name: Disallow root login
  ansible.builtin.copy:
    src: disableRootLogin.conf
    dest: /etc/ssh/sshd_config.d/disableRootLogin.conf
  notify: restart ssh
  
- name: Change ssh port
  ansible.builtin.template:
    src: changePort.j2
    dest: /etc/ssh/sshd_config.d/changePort.conf
  notify: restart ssh